# File name: Proj_lib_Input_Latch_schematic.S.
# Subcircuit for cell: Input_Latch.
# Generated for: hspiceS.
# Generated on Nov 30 19:09:20 2014.

XI25 net172 GD clk_in_4 VD sub1 
XI24 net172 GD clk_in_3 VD sub1 
XI23 net172 GD clk_in_2 VD sub1 
XI22 net172 GD clk_in_1 VD sub1 
XI17 clk GD net172 VD sub1 
XI16 B_0 GD oB_0 VD clk_in_3 sub2 
XI15 B_1 GD oB_1 VD clk_in_3 sub2 
XI14 B_2 GD oB_2 VD clk_in_3 sub2 
XI13 B_3 GD oB_3 VD clk_in_3 sub2 
XI12 B_4 GD oB_4 VD clk_in_4 sub2 
XI11 B_5 GD oB_5 VD clk_in_4 sub2 
XI10 B_6 GD oB_6 VD clk_in_4 sub2 
XI9 B_7 GD oB_7 VD clk_in_4 sub2 
XI8 A_7 GD oA_7 VD clk_in_2 sub2 
XI7 A_6 GD oA_6 VD clk_in_2 sub2 
XI6 A_5 GD oA_5 VD clk_in_2 sub2 
XI5 A_4 GD oA_4 VD clk_in_2 sub2 
XI4 A_3 GD oA_3 VD clk_in_1 sub2 
XI3 A_2 GD oA_2 VD clk_in_1 sub2 
XI2 A_1 GD oA_1 VD clk_in_1 sub2 
XI0 A_0 GD oA_0 VD clk_in_1 sub2 



