# File name: Proj_lib_Output_Latch_schematic.S.
# Subcircuit for cell: Output_Latch.
# Generated for: hspiceS.
# Generated on Nov 30 19:44:00 2014.

# terminal mapping: GD = GD
#                   VD = VD
#                   clk = clk
#                   oli_0 = oli_0
#                   oli_1 = oli_1
#                   oli_2 = oli_2
#                   oli_3 = oli_3
#                   oli_4 = oli_4
#                   oli_5 = oli_5
#                   oli_6 = oli_6
#                   oli_7 = oli_7
#                   oli_8 = oli_8
#                   oli_9 = oli_9
#                   oli_10 = oli_10
#                   oli_11 = oli_11
#                   oli_12 = oli_12
#                   oli_13 = oli_13
#                   oli_14 = oli_14
#                   oli_15 = oli_15
#                   oli_16 = oli_16
#                   oli_17 = oli_17
#                   oli_18 = oli_18
#                   oli_19 = oli_19
#                   oli_20 = oli_20
#                   oli_21 = oli_21
#                   oli_22 = oli_22
#                   oli_23 = oli_23
#                   oli_24 = oli_24
#                   oli_25 = oli_25
#                   olo_0 = olo_0
#                   olo_1 = olo_1
#                   olo_2 = olo_2
#                   olo_3 = olo_3
#                   olo_4 = olo_4
#                   olo_5 = olo_5
#                   olo_6 = olo_6
#                   olo_7 = olo_7
#                   olo_8 = olo_8
#                   olo_9 = olo_9
#                   olo_10 = olo_10
#                   olo_11 = olo_11
#                   olo_12 = olo_12
#                   olo_13 = olo_13
#                   olo_14 = olo_14
#                   olo_15 = olo_15
#                   olo_16 = olo_16
#                   olo_17 = olo_17
#                   olo_18 = olo_18
#                   olo_19 = olo_19
#                   olo_20 = olo_20
#                   olo_21 = olo_21
#                   olo_22 = olo_22
#                   olo_23 = olo_23
#                   olo_24 = olo_24
#                   olo_25 = olo_25
.SUBCKT &1 GD VD clk oli_0 oli_1 oli_2 oli_3 oli_4 oli_5 oli_6 oli_7 oli_8 &
oli_9 oli_10 oli_11 oli_12 oli_13 oli_14 oli_15 oli_16 oli_17 oli_18 &
oli_19 oli_20 oli_21 oli_22 oli_23 oli_24 oli_25 olo_0 olo_1 olo_2 olo_3 &
olo_4 olo_5 olo_6 olo_7 olo_8 olo_9 olo_10 olo_11 olo_12 olo_13 olo_14 &
olo_15 olo_16 olo_17 olo_18 olo_19 olo_20 olo_21 olo_22 olo_23 olo_24 &
olo_25 
XI31 net348 GD net320 VD sub2 
XI32 net320 GD clk_out_1 VD sub2 
XI34 net320 GD clk_out_3 VD sub2 
XI33 net320 GD clk_out_2 VD sub2 
XI26 net352 GD clk_out_6 VD sub2 
XI27 net352 GD clk_out_5 VD sub2 
XI28 net352 GD clk_out_4 VD sub2 
XI29 net352 GD net348 VD sub2 
XI30 clk GD net352 VD sub2 
XI25 oli_25 GD olo_25 VD clk_out_1 sub7 
XI21 oli_24 GD olo_24 VD clk_out_2 sub7 
XI22 oli_21 GD olo_21 VD clk_out_1 sub7 
XI23 oli_22 GD olo_22 VD clk_out_1 sub7 
XI24 oli_23 GD olo_23 VD clk_out_1 sub7 
XI20 oli_16 GD olo_16 VD clk_out_6 sub7 
XI19 oli_17 GD olo_17 VD clk_out_6 sub7 
XI18 oli_18 GD olo_18 VD clk_out_6 sub7 
XI17 oli_19 GD olo_19 VD clk_out_6 sub7 
XI1 oli_20 GD olo_20 VD clk_out_6 sub7 
XI0 oli_0 GD olo_0 VD clk_out_2 sub7 
XI2 oli_1 GD olo_1 VD clk_out_2 sub7 
XI3 oli_2 GD olo_2 VD clk_out_2 sub7 
XI4 oli_3 GD olo_3 VD clk_out_3 sub7 
XI5 oli_4 GD olo_4 VD clk_out_3 sub7 
XI6 oli_5 GD olo_5 VD clk_out_3 sub7 
XI7 oli_6 GD olo_6 VD clk_out_3 sub7 
XI8 oli_7 GD olo_7 VD clk_out_4 sub7 
XI9 oli_15 GD olo_15 VD clk_out_6 sub7 
XI10 oli_14 GD olo_14 VD clk_out_5 sub7 
XI11 oli_13 GD olo_13 VD clk_out_5 sub7 
XI12 oli_12 GD olo_12 VD clk_out_5 sub7 
XI13 oli_11 GD olo_11 VD clk_out_5 sub7 
XI14 oli_10 GD olo_10 VD clk_out_4 sub7 
XI15 oli_9 GD olo_9 VD clk_out_4 sub7 
XI16 oli_8 GD olo_8 VD clk_out_4 sub7 



# End of subcircuit definition.
.ENDS &1
