# File name: Proj_lib_HALF_ADDER_22_STATIC_CMOS_schematic.S.
# Subcircuit for cell: HALF_ADDER_22_STATIC_CMOS.
# Generated for: hspiceS.
# Generated on Nov  3 12:49:08 2014.

# terminal mapping: A_IN = A_IN
#                   B_IN = B_IN
#                   C_OUT_HALF_ADDER22 = 2
#                   S_OUT_HALF_ADDER22 = 1
.SUBCKT &1 A_IN B_IN 2 1 
XI1 A_IN B_IN 2 sub2 
XI0 A_IN B_IN 1 sub3 



# End of subcircuit definition.
.ENDS &1
